name: Prerelease Package

on:
  pull_request:
    branches:
      - master

jobs:
  Publish-prerelease:
    if: contains(github.head_ref, 'alpha') || contains(github.head_ref, 'beta') || contains(github.head_ref, 'prerelease')
    runs-on: ubuntu-latest
   
    env:
      USERNAME: cadu1982
      REPO: cadu1982/github-actions
      CAMINHO_PROJETO: ./Groffe.Distancias/Groffe.Distancias.csproj
      DIR: ${{ github.workspace }}/output

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
         
    - uses: actions/checkout@v3 # consulta actions
    - id: prerelease-suffix # identificação da ação para outputs
      uses: cadu1982/hello-action@v1 # referencia a action a ser usada
     
    - name: Semantic versioning
      id: versioning
      uses: paulhatch/semantic-version@v4.0.2
      with:
        tag_prefix: ''
        major_pattern: "break:"
        minor_pattern: "feat:"
        patch_pattern: "fix:"
        format: "${major}.${minor}.${patch}-${{ steps.prerelease-suffix.outputs.prerelease_suffix }}${increment}"
        
    - name: Build Project and Generate Package
      run: dotnet pack ${{ env.CAMINHO_PROJETO }} -c Release -p:PackageVersion=${{ steps.versioning.outputs.version }} -o ${{ env.DIR }}

    - name: Push Package on GitHub Package Registry
      run: |
        dotnet nuget add source --username USERNAME --password ${{ secrets.MY_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/cadu1982/index.json"
        dotnet nuget push '${{ env.DIR }}/*.nupkg' --api-key ${{ secrets.MY_TOKEN }} --source github --skip-duplicate
    
    - name: Create Release
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      with:
        tag_name: ${{ steps.versioning.outputs.version }}
        release_name: ${{ steps.versioning.outputs.version }}
        prerelease: true