name: script #Reusable workflow

on:
  workflow_call:
    # Map the workflow outputs to job outputs
    outputs:
      firstword:
        description: "The first output string"
        value: ${{ jobs.example_job.outputs.output1 }}
      

jobs:
  example_job:
    name: Generate output
    runs-on: ubuntu-latest
    # Map the job outputs to step outputs
    outputs:
      output1: ${{ steps.get-prerelease-suffix.outputs.prerelease_suffix }}
      
    steps:
          
      - name: Find the specific suffix to compose the version format
        run: |
          import re
          import os
          github_head_ref = "${{ github.head_ref }}"
          name_branch = github_head_ref.lower()
          suffix_array = re.findall("alpha|beta|prerelease", name_branch)
          env_file = os.getenv('GITHUB_ENV')
          with open(env_file, "a") as myfile:
          myfile.write("PRERELEASE=" + suffix_array[0])
        shell: python
  
      - name: Set prerelease suffix as output
        id: get-prerelease-suffix
        run: echo "::set-output name=prerelease_suffix::$(echo $PRERELEASE)"
        shell: bash